name              'common'
maintainer        'Yasuhisa Yamazaki'
maintainer_email  'yasu@amrael.net'
description       'general cookbook'
version           '0.0.1'

depends 'python'
depends 'postfix'
depends 's3_file'
depends 'ssh_ignore_host'
depends 'gunicorn'
depends 'supervisor'
depends 'nginx'
depends 'td-agent'