name              'api'
maintainer        'Yasuhisa Yamazaki'
maintainer_email  'yasu@amrael.net'
description       'for api'
version           '0.0.1'

depends 'python'
depends 'gunicorn'
depends 'nginx'
depends 'chef-td-agent'