name              'api'
maintainer        'Yasuhisa Yamazaki'
maintainer_email  'yasu@amrael.net'
description       'for api'
version           '0.0.1'

depends 'python'
depends 'supervisor'
depends 'gunicorn'
depends 'nginx'
depends 'td-agent'
depends 's3'
depends 'postfix'
depends 'ssh_ignore_host'
